---
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: master
rule_files:
- "/etc/prometheus/alert.rules"
scrape_configs:
- job_name: prometheus
  scrape_interval: 10s
  scrape_timeout: 10s
  static_configs:
  - targets:
    - localhost:9090
    labels:
      alias: Prometheus
- job_name: node
  file_sd_configs:
  - files:
    - "/etc/prometheus/file_sd_config.d/node_*.yaml"
alerting:
  alert_relabel_configs: []
  alertmanagers: []
remote_read: []
remote_write: []

